pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux'
                    args '-it --entrypoint=/bin/bash'
                }
            }
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
        }
    }
}
